In [383]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split


In [384]:
df = pd.read_excel('DataBalita.xlsx')
df

NO             NAMA_ANAK JK  Usia    BB     TB  Stunting
0      1    Nabila Hasna Amira  P    58  14.8  102.1    Normal
1      2    Marta Emi Masithoh  P    57  12.3   93.3    Normal
2      3   Nizama Kenzo Alvero  L    57  13.8  101.0    Normal
3      4  Haikal Cahya Wardana  L    57  14.8  102.3    Normal
4      5    Arsy Hilma Fadhila  P    59  14.1   97.5    Normal
..   ...                   ... ..   ...   ...    ...       ...
186  187   Qurota Ayunindya S.  P     3   4.0   59.6    Normal
187  188       Lubna Alifia K.  P     3   3.7   55.1    Normal
188  189    Rayyanza Kenzie I.  L     1   3.5   54.5  Obesitas
189  190       Fazana Mayra R.  P     1   3.4   52.5  Obesitas
190  191     Vanya Afsheena R.  P     1   4.0   53.5  Obesitas

[191 rows x 7 columns]

In [385]:
df = df.replace (["Gizi Buruk"], 0)
df = df.replace (["Gizi Kurang"], 1)
df = df.replace (["Normal"], 2)
df = df.replace (["Obesitas"], 3)
df.head(10)

NO               NAMA_ANAK JK  Usia    BB     TB  Stunting
0   1      Nabila Hasna Amira  P    58  14.8  102.1         2
1   2      Marta Emi Masithoh  P    57  12.3   93.3         2
2   3     Nizama Kenzo Alvero  L    57  13.8  101.0         2
3   4    Haikal Cahya Wardana  L    57  14.8  102.3         2
4   5      Arsy Hilma Fadhila  P    59  14.1   97.5         2
5   6          Fano Irwansyah  L    59  16.1   92.1         2
6   7  Alvin Zaidan Syafiulla  L    59  13.0   93.3         2
7   8      Naura Shafa Azizah  P    59  10.1   88.3         2
8   9  Muhammad Ali Al-Furqon  L    58  12.9   95.1         2
9  10  Muamar Hafiz Ramadhani  L    58  14.1   94.5         2

In [386]:
df = df.replace (["P"], 0)
df = df.replace (["L"], 1)
df.head(20)

NO                     NAMA_ANAK  JK  Usia    BB     TB  Stunting
0    1            Nabila Hasna Amira   0    58  14.8  102.1         2
1    2            Marta Emi Masithoh   0    57  12.3   93.3         2
2    3           Nizama Kenzo Alvero   1    57  13.8  101.0         2
3    4          Haikal Cahya Wardana   1    57  14.8  102.3         2
4    5            Arsy Hilma Fadhila   0    59  14.1   97.5         2
5    6                Fano Irwansyah   1    59  16.1   92.1         2
6    7        Alvin Zaidan Syafiulla   1    59  13.0   93.3         2
7    8            Naura Shafa Azizah   0    59  10.1   88.3         2
8    9        Muhammad Ali Al-Furqon   1    58  12.9   95.1         2
9   10        Muamar Hafiz Ramadhani   1    58  14.1   94.5         2
10  11         Handika Putra Hafiz N   1    58  12.0   94.4         2
11  12                Andika Pratama   1    57  16.2   97.9         2
12  13        Aditya Zainul Muttaqin   1    55  14.9   95.6         2
13  14      Ernest Funky Oktaryan .P   1    54  11.7   88.4         2
14  15            Alvino Dwi Saputra   1    55  13.6   89.7         2
15  16       Khalifa Azzahra Jailani   0    50  12.3   91.2         2
16  17          Fernando Ahmad Rifai   1    50  11.8   91.3         2
17  18        Arshaka Aldhien Andani   1    49  22.7  103.1         2
18  19     Aletta Khasandra Setiawan   0    44  11.8   85.1         2
19  20  Ifa Nur Hafidzah Mu'isdzah.K   0    47  14.9   97.8         2

In [387]:
df = df.drop("NAMA_ANAK", axis=1); axis=1

In [388]:
df.shape

(191, 6)

In [389]:
df.dtypes

NO            int64
JK            int64
Usia          int64
BB          float64
TB          float64
Stunting      int64
dtype: object

In [390]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191 entries, 0 to 190
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   NO        191 non-null    int64  
 1   JK        191 non-null    int64  
 2   Usia      191 non-null    int64  
 3   BB        191 non-null    float64
 4   TB        191 non-null    float64
 5   Stunting  191 non-null    int64  
dtypes: float64(2), int64(4)
memory usage: 9.1 KB


In [391]:
df["JK"] = df["JK"].astype("float")

In [392]:
df["Stunting"] = df["Stunting"].astype("float")

In [393]:
df["Usia"] = df["Usia"].astype("float")

In [394]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191 entries, 0 to 190
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   NO        191 non-null    int64  
 1   JK        191 non-null    float64
 2   Usia      191 non-null    float64
 3   BB        191 non-null    float64
 4   TB        191 non-null    float64
 5   Stunting  191 non-null    float64
dtypes: float64(5), int64(1)
memory usage: 9.1 KB


In [395]:
df = df.drop("NO", axis=1); axis=1

In [396]:
df.describe

<bound method NDFrame.describe of       JK  Usia    BB     TB  Stunting
0    0.0  58.0  14.8  102.1       2.0
1    0.0  57.0  12.3   93.3       2.0
2    1.0  57.0  13.8  101.0       2.0
3    1.0  57.0  14.8  102.3       2.0
4    0.0  59.0  14.1   97.5       2.0
..   ...   ...   ...    ...       ...
186  0.0   3.0   4.0   59.6       2.0
187  0.0   3.0   3.7   55.1       2.0
188  1.0   1.0   3.5   54.5       3.0
189  0.0   1.0   3.4   52.5       3.0
190  0.0   1.0   4.0   53.5       3.0

[191 rows x 5 columns]>

In [397]:
import matplotlib.pyplot as plt 
import seaborn as sns 
%matplotlib inline 

In [398]:
X = df.drop(columns='Stunting') 
X.head()

JK  Usia    BB     TB
0  0.0  58.0  14.8  102.1
1  0.0  57.0  12.3   93.3
2  1.0  57.0  13.8  101.0
3  1.0  57.0  14.8  102.3
4  0.0  59.0  14.1   97.5

In [399]:
y = df['Stunting']
y.head()

0    2.0
1    2.0
2    2.0
3    2.0
4    2.0
Name: Stunting, dtype: float64

In [400]:
scaler = StandardScaler()

In [401]:
scaler.fit(X)

StandardScaler()

In [402]:
standarized_data = scaler.transform(X)

In [403]:
print(standarized_data)

[[-0.96399841  1.50832428  0.59315841  1.06900234]
 [-0.96399841  1.44968598  0.03351972  0.45014888]
 [ 1.03734611  1.44968598  0.36930294  0.99164566]
 [ 1.03734611  1.44968598  0.59315841  1.0830672 ]
 [-0.96399841  1.56696257  0.43645958  0.74551076]
 [ 1.03734611  1.56696257  0.88417053  0.36575977]
 [ 1.03734611  1.56696257  0.19021855  0.45014888]
 [-0.96399841  1.56696257 -0.45896233  0.0985276 ]
 [ 1.03734611  1.50832428  0.16783301  0.57673255]
 [ 1.03734611  1.50832428  0.43645958  0.53453799]
 [ 1.03734611  1.50832428 -0.03363692  0.52750557]
 [ 1.03734611  1.44968598  0.90655608  0.77364046]
 [ 1.03734611  1.3324094   0.61554396  0.61189467]
 [ 1.03734611  1.2737711  -0.10079357  0.10556002]
 [ 1.03734611  1.3324094   0.32453184  0.19698156]
 [-0.96399841  1.03921793  0.03351972  0.30246794]
 [ 1.03734611  1.03921793 -0.07840802  0.30950037]
 [ 1.03734611  0.98057963  2.36161669  1.1393266 ]
 [-0.96399841  0.68738816 -0.07840802 -0.12651002]
 [-0.96399841  0.86330305  0.61

In [404]:
X = standarized_data
y = df['Stunting']

In [405]:
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score,confusion_matrix, classification_report 

# Naive Bayes

In [406]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, test_size=0.2, random_state=10)

In [407]:
classifier = classifier.fit(X_train2, y_train2)

In [408]:
predicted = classifier.predict(X_test2)

In [409]:
print(classifier.score(X_test2, y_test2))

1.0


In [410]:
y_true = y_test2
y_pred2 = predicted
print(accuracy_score(y_true, y_pred2))

1.0


In [411]:
print(confusion_matrix(y_test2, y_pred2))
print(classification_report(y_test2, y_pred2))

[[38  0]
 [ 0  1]]
              precision    recall  f1-score   support

         2.0       1.00      1.00      1.00        38
         3.0       1.00      1.00      1.00         1

    accuracy                           1.00        39
   macro avg       1.00      1.00      1.00        39
weighted avg       1.00      1.00      1.00        39



#  KNN


In [412]:
from sklearn.neighbors import KNeighborsClassifier

In [413]:
X_train3, X_test3, y_train3, y_test3 = train_test_split(X, y, test_size=0.2, random_state=10)


In [414]:
knn=KNeighborsClassifier(n_neighbors=2)


In [415]:
knn.fit(X_train3,y_train3)


KNeighborsClassifier(n_neighbors=2)

In [416]:
knn.score(X_test3,y_test3)


0.9743589743589743

In [417]:
y_pred3 = knn.predict(X_test3)
print(confusion_matrix(y_test3, y_pred3))
print(classification_report(y_test3, y_pred3))

[[38  0]
 [ 1  0]]
              precision    recall  f1-score   support

         2.0       0.97      1.00      0.99        38
         3.0       0.00      0.00      0.00         1

    accuracy                           0.97        39
   macro avg       0.49      0.50      0.49        39
weighted avg       0.95      0.97      0.96        39



C:\Users\PERSONAL\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PERSONAL\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PERSONAL\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf

In [418]:
import pickle

In [419]:
filename = 'data_balita.sav'
pickle.dump(classifier, open(filename,'wb'))